version: '3.8'
services:
  next-app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    stdin_open: true
    tty: true
    environment:
      - PORT=3000
    command: yarn start